version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g typescript
      - npm install -g yarn
      - npm install -g tsdx
      - npm install -g ts-node
  pre_build:
    commands:
      - echo Prebuild
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - node_modules/**/*
artifacts:
  type: zip
  files: 
    - dist/**/*
    - yarn.lock
    - package.json
    - tsconfig.json
  name: collard-lookup-`date`
